src/Entity/Classroom.php
<?php

namespace App\Entity;

use App\Repository\ClassroomRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ClassroomRepository::class)
 */
class Classroom
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=55)
     */
    private $Name;

    /**
     * @ORM\OneToMany(targetEntity=Student::class, mappedBy="classroom")
     */
    private $students;

    /**
     * @ORM\OneToMany(targetEntity=Etudiant::class, mappedBy="classroom")
     */
    private $etudiants;

    public function __construct()
    {
        $this->students = new ArrayCollection();
        $this->etudiants = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    /**
     * @return Collection|Student[]
     */
    public function getStudents(): Collection
    {
        return $this->students;
    }

    public function addStudent(Student $student): self
    {
        if (!$this->students->contains($student)) {
            $this->students[] = $student;
            $student->setClassroom($this);
        }

        return $this;
    }

    public function removeStudent(Student $student): self
    {
        if ($this->students->removeElement($student)) {
            // set the owning side to null (unless already changed)
            if ($student->getClassroom() === $this) {
                $student->setClassroom(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Etudiant[]
     */
    public function getEtudiants(): Collection
    {
        return $this->etudiants;
    }

    public function addEtudiant(Etudiant $etudiant): self
    {
        if (!$this->etudiants->contains($etudiant)) {
            $this->etudiants[] = $etudiant;
            $etudiant->setClassroom($this);
        }

        return $this;
    }

    public function removeEtudiant(Etudiant $etudiant): self
    {
        if ($this->etudiants->removeElement($etudiant)) {
            // set the owning side to null (unless already changed)
            if ($etudiant->getClassroom() === $this) {
                $etudiant->setClassroom(null);
            }
        }

        return $this;
    }
}

src/Entity/Student.php
<?php

namespace App\Entity;

use App\Repository\StudentRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=StudentRepository::class)
 */
class Student
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     */
    private $I;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Email;

    /**
     * @ORM\Column(type="integer")
     */
    private $CIN;

    /**
     * @ORM\ManyToOne(targetEntity=Classroom::class, inversedBy="students")
     */
    private $classroom;

    public function getNSC(): ?int
    {
        return $this->NSC;
    }
    public function setNSC(int $NSC): self
    {
        $this->NSC = $NSC;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->Email;
    }

    public function setEmail(string $Email): self
    {
        $this->Email = $Email;

        return $this;
    }

    public function getCIN(): ?int
    {
        return $this->CIN;
    }

    public function setCIN(int $CIN): self
    {
        $this->CIN = $CIN;

        return $this;
    }

    public function getClassroom(): ?Classroom
    {
        return $this->classroom;
    }

    public function setClassroom(?Classroom $classroom): self
    {
        $this->classroom = $classroom;

        return $this;
    }
}

src/Form/StudentType.php
<?php

namespace App\Form;

use App\Entity\Classroom;
use App\Entity\Student;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class StudentType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('NSC',TextareaType::class)
            ->add('Email',TextareaType::class)
            ->add('CIN',TextareaType::class)
            ->add('classroom',EntityType::class,['class'=>Classroom::class,
                'choice_label'=>'name'])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Student::class,
        ]);
    }
}

src/Controller/StudentController.php
<?php

namespace App\Controller;

use App\Entity\Student;
use App\Form\SearchStudentType;
use App\Form\StudentType;
use App\Repository\StudentRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class StudentController extends AbstractController
{
    /**
     * @Route("/student", name="student")
     */
    public function index(): Response
    {
        return $this->render('student/index.html.twig', [
            'controller_name' => 'StudentController',
        ]);
    }
    /**
     * @Route("/studentList", name="studentList")
     */
    public function readStudent()
    {
        $repository = $this->getDoctrine()->getRepository(Student::class);
        $strudents = $repository->findAll();
        // order By mail
       // $studentByMail = $repository->orderByMail();
        return $this->render('student/read.html.twig', [
            'students' => $strudents,
        ]);
    }
    /**
     * @Route("/deleteStudent/{nsc}", name="deleteStudent")
     */
    public function deleteStudent($nsc)
    {
        $em = $this->getDoctrine()->getManager();
        $student = $em->getRepository(Student::class)->find($nsc);
        $em->remove($student);
        $em->flush();
        return $this->redirectToRoute("studentList");
    } /**
 * @Route("/addStudent", name="addStudent")
 */
    public function addStudent(Request $request)
    {
        $student = new Student();
        $form = $this->createForm(StudentType::class,
            $student);
        $form->add('Ajouter', SubmitType::class);
        $form->handleRequest($request);
        if ($form->isSubmitted()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($student);
            $em->flush();
            return $this->redirectToRoute('studentList');
        }
        return $this->render('student/newStudent.html.twig', [
            'f' => $form->createView(),
        ]);
    }
    /**
     * @Route("/listStudent", name="listStudent")
     */
    public function listStudent(StudentRepository $repository)
    {
        //$repository = $this->getDoctrine()->getRepository(Student::class);
       // $strudents = $repository->findAll();
        // order By mail
        $studentByMail = $repository->orderByMail();
        return $this->render('student/readbymail.html.twig', [
            'students' => $studentByMail,
        ]);
    }
    /**
     * @Route("/listStudentComplexe", name="listStudentComplexe")
     */
    public function listStudentComplexe(StudentRepository $repository,Request $request)
    {
        //$repository = $this->getDoctrine()->getRepository(Student::class);
        $students = $repository->findAll();
        // order By mail
        $studentsByMail = $repository->orderByMail();
        //search
        $searchForm = $this->createForm(SearchStudentType::class);
        $searchForm->handleRequest($request);
        if ($searchForm->isSubmitted()) {
            $nsc = $searchForm->getData()->getNsc();
            $resultOfSearch = $repository->searchStudent($nsc);
            return $this->render('student/searchStudent.html.twig', array(
                "resultOfSearch" => $resultOfSearch,
                "searchStudent" => $searchForm->createView()));
        }
        return $this->render('student/readComplexe.html.twig', array(
            "students" => $students,
            "studentsByMail" => $studentsByMail,
            "searchStudent" => $searchForm->createView()));
    }


}

templates/student/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello StudentController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/Users/Yasmine Boutrif/composer/mydir/src/Controller/StudentController.php'|file_link(0) }}">src/Controller/StudentController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/Users/Yasmine Boutrif/composer/mydir/templates/student/index.html.twig'|file_link(0) }}">templates/student/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/student/newStudent.html.twig
<h1> Ajouter student </h1>
{{form(f)}}

templates/student/read.html.twig
<h1>afficher students list</h1>
<table border="1">
    <tr>
    <th>NSC</th>
    <th>Email</th>
        <th>Classroom</th>
        <th>CIN</th>
        <th>Supprimer</th>
    </tr>
    {% for student in students %}
        <tr>
            <td>{{ student.nsc }}</td>
            <td>{{ student.email }}</td>
            <td>{{ student.classroom.name }}</td>
            <td>{{ student.cin }}</td>
            <td>
                <a href="{{ path('deleteStudent',{'nsc':student.nsc})}}">Supprimer</a>
            </td>
        </tr>

    {% endfor %}

</table>
<a href="{{ path('addStudent') }}">ajouter un element</a>

templates/student/readComplexe.html.twig
{{form_start (searchStudent)}}
{{form_widget (searchStudent)}}
<button  type = " submit "  style = " text-align: end " > Rechercher </button >
{{form_end ( searchStudent )}}
<h1>afficher students list</h1>
<table border="1">
    <tr>
        <th>NSC</th>
        <th>Email</th>
        <th>Classroom</th>
        <th>CIN</th>
        <th>Supprimer</th>
    </tr>
    {% for student in students %}
        <tr>
            <td>{{ student.nsc }}</td>
            <td>{{ student.email }}</td>
            <td>{{ student.classroom.name }}</td>
            <td>{{ student.cin }}</td>
            <td>
                <a href="{{ path('deleteStudent',{'nsc':student.nsc})}}">Supprimer</a>
            </td>
        </tr>

    {% endfor %}

</table>
<a href="{{ path('addStudent') }}">ajouter un element</a>



<h1>afficher students list by mail</h1>
<table border="1">
    <tr>
        <th>NSC</th>
        <th>Email</th>
        <th>Classroom</th>
        <th>CIN</th>
        <th>Supprimer</th>
    </tr>
    {% for student in studentsByMail %}
        <tr>
            <td>{{ student.nsc }}</td>
            <td>{{ student.email }}</td>
            <td>{{ student.classroom.name }}</td>
            <td>{{ student.cin }}</td>
            <td>
                <a href="{{ path('deleteStudent',{'nsc':student.nsc})}}">Supprimer</a>
            </td>
        </tr>

    {% endfor %}

</table>
<a href="{{ path('addStudent') }}">ajouter un element</a>

templates/student/readbymail.html.twig
<h1>afficher students list</h1>
<table border="1">
    <tr>
        <th>NSC</th>
        <th>Email</th>
        <th>Classroom</th>
        <th>CIN</th>
        <th>Supprimer</th>
    </tr>
    {% for student in students %}
        <tr>
            <td>{{ student.nsc }}</td>
            <td>{{ student.email }}</td>
            <td>{{ student.classroom.name }}</td>
            <td>{{ student.cin }}</td>
            <td>
                <a href="{{ path('deleteStudent',{'nsc':student.nsc})}}">Supprimer</a>
            </td>
        </tr>

    {% endfor %}

</table>
<a href="{{ path('addStudent') }}">ajouter un element</a>

templates/student/searchStudent.html.twig
{{form_start (searchStudent)}}
{{form_widget (searchStudent)}}
<button  type = " submit "  style = " text-align: end " > Rechercher </button >
{{form_end ( searchStudent )}}

<h1>afficher students list</h1>
<table border="1">
    <tr>
        <th>NSC</th>
        <th>Email</th>
        <th>Classroom</th>
        <th>CIN</th>
        <th>Supprimer</th>
    </tr>
    {% for student in resultOfSearch %}
        <tr>
            <td>{{ student.nsc }}</td>
            <td>{{ student.email }}</td>
            <td>{{ student.classroom.name }}</td>
            <td>{{ student.cin }}</td>
            <td>
                <a href="{{ path('deleteStudent',{'nsc':student.nsc})}}">Supprimer</a>
            </td>
        </tr>

    {% endfor %}

</table>
<a href="{{ path('addStudent') }}">ajouter un element</a>